name: Terraform Continuous Deploy

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    name: Terraform CD
    environment:
      name: cd
    strategy:
      matrix:
        env: [mintak]

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup
        uses: ./.github/actions/setup
        with:
          workload_identity_provider: "projects/917389335203/locations/global/workloadIdentityPools/github/providers/github-provider"
          service_account: "github-actions@mintak-h83y.iam.gserviceaccount.com"
          directory: ./environments/${{ matrix.env }}

      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./environments/${{ matrix.env }}

      - name: Set status success
        id: status-success
        if: steps.apply.outcome == 'success'
        run: echo "color=good" >> $GITHUB_ENV

      - name: Set status failure
        id: status-failure
        if: failure()
        run: echo "color=danger" >> $GITHUB_ENV

      - name: Notify slack success
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@212e9f7a9ca33368c8dd879d6053972128258985 # v1.5.0
        with:
          channel: notifications
          status: "${{ steps.apply.outcome }}(actor is ${{ github.actor }})"
          color: ${{ env.color }}
